In [2]:
a = [1, 2, 3, 4, 5]

In [3]:
b = [1, 2, 3, 4, 5, 6]

In [4]:
print(a + b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6]


In [5]:
result = []

for x, y in zip(a, b):
    result.append( x + y)

In [6]:
result

[2, 4, 6, 8, 10]

In [8]:
import numpy as np

In [9]:
a = np.array([1, 2, 3, 4])

In [10]:
a.dtype

dtype('int64')

In [11]:
a = np.array([1.2, 3.4, 5.6, 7.8, 9.0])

In [12]:
a.dtype

dtype('float64')

In [16]:
a[0] = 10
print(a)
a.dtype

[10.   3.4  5.6  7.8  9. ]


dtype('float64')

In [18]:
a.ndim

1

In [19]:
a.size

5

In [23]:
a = np.array([1, 2, 3, 4, 5])
f = np.array([1.2, 2.3, 3.4, 4.5, 6.7])
print( a + f)
print( a - f)
print( a * f)
print( a / f)
print( a // f)
print( a % f)
print( a ** f)

[ 2.2  4.3  6.4  8.5 11.7]
[-0.2 -0.3 -0.4 -0.5 -1.7]
[ 1.2  4.6 10.2 18.  33.5]
[0.83333333 0.86956522 0.88235294 0.88888889 0.74626866]
[0. 0. 0. 0. 0.]
[1. 2. 3. 4. 5.]
[1.00000000e+00 4.92457765e+00 4.18998305e+01 5.12000000e+02
 4.82057705e+04]


Universal function (ufuncs)

In [24]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])