In [2]:
a = [1, 2, 3, 4, 5]

In [3]:
b = [1, 2, 3, 4, 5, 6]

In [4]:
print(a + b)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6]


In [5]:
result = []

for x, y in zip(a, b):
    result.append( x + y)

In [6]:
result

[2, 4, 6, 8, 10]

In [2]:
import numpy as np

In [9]:
a = np.array([1, 2, 3, 4])

In [10]:
a.dtype

dtype('int64')

In [11]:
a = np.array([1.2, 3.4, 5.6, 7.8, 9.0])

In [12]:
a.dtype

dtype('float64')

In [16]:
a[0] = 10
print(a)
a.dtype

[10.   3.4  5.6  7.8  9. ]


dtype('float64')

In [18]:
a.ndim

1

In [19]:
a.size

5

In [23]:
a = np.array([1, 2, 3, 4, 5])
f = np.array([1.2, 2.3, 3.4, 4.5, 6.7])
print( a + f)
print( a - f)
print( a * f)
print( a / f)
print( a // f)
print( a % f)
print( a ** f)

[ 2.2  4.3  6.4  8.5 11.7]
[-0.2 -0.3 -0.4 -0.5 -1.7]
[ 1.2  4.6 10.2 18.  33.5]
[0.83333333 0.86956522 0.88235294 0.88888889 0.74626866]
[0. 0. 0. 0. 0.]
[1. 2. 3. 4. 5.]
[1.00000000e+00 4.92457765e+00 4.18998305e+01 5.12000000e+02
 4.82057705e+04]


Universal function (ufuncs)

In [24]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [25]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [3]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a.dtype

dtype('int64')

In [4]:
a.size

10

In [5]:
a.shape

(2, 5)

In [6]:
a.ndim

2

In [10]:
a[1, 2] = 12
a[1]

array([ 6,  7, 12,  9, 10])

NumPy : Indexing and Slicing

In [11]:
a = np.array([10, 11, 12, 13, 14])
a[1:3]

array([11, 12])

In [ ]:
# var[lower : upper : step] here we ahve lower bond and upper bond and steps for each element


print(a[1:-2])  # means strip off first element and last two element then return stripped array
print(a[-4:3])
print(a[:3])  # grab first 3 elements
print(a[-2:])  # grab last two elements
print(a[::2])  # here there is no start there is no end , stride is 2 ( means that it takes two steps)

[11 12]
[11 12]
[10 11 12]
[13 14]
[10 12 14]


Array Slicing

In [22]:
# slicing works much like standard python slicing


a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])

print(a)

a[4:, 4:]

a[:, 2]

a[2::2,::2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[11, 13, 15],
       [21, 23, 25]])

In [ ]:
a = np.arange(25).reshape(5,5)

print(a[4,:])

print(a[:, 1::2])

print(a[1::2, 0:3:2])

[20 21 22 23 24]
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]
[[ 5  7]
 [15 17]]


In [ ]:
# copying array using colon ( : )

a = np.array([1, 2, 3, 4, 5])

b = a[:2]

b[0] = -1 # changed 0th index to -1

print(b)

print(a) # here as we can see changing b has effect on a

[-1  2]
[-1  2  3  4  5]


Explanation :  What's happening here is that we have some array a = [1, 2, 3, 4, 5], when we slice it and say that it is b array
then it doesn't create a new array but it just look for sliced part and place it in b, so the 2 array shares the same memory location, 
So changing in b also change a because of same memory location.

In [6]:
a = np.array([1, 2, 3, 4, 5])

print(a[-2:])

a[-2:] = [11, 12]   # replaces intire sliced array with another array

a[-2:] = 25  # replaces intire array with array of same dimention but all filled element would be 25

[4 5]


Dunder method :  it's like undercore things that is happening when we doing something like a[0] = 100 i.e. assigning a value

In [ ]:
#underling principle of python when i wrote this code

a.__setitem__(0, 100)  # var.__setitem__(position, value) is python code where it set value 100 at index 0

# it is same as a[0] = 100


np.array.__call__([1, 2, 3]) # it is same as np.array([1,2,3])

a.__len__() # same as len(a)

5